# Generated by Django 3.2.5 on 2021-10-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images_and_Prediction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.BinaryField()),
                ('detected_numbers', models.BinaryField()),
                ('prediction', models.CharField(max_length=200)),
            ],
        ),
    ]
